### ISSUE TITLE
NodeJS container using Istio cannot connect to non-istiofied headless Kafka service

### ISSUE THREAD

**Issue by FuzzOli87** [istio/issues#37]
Hello,

I've been discussing this issue in the Users Group here:
 [https://groups.google.com/forum/#!topic/istio-users/wLyQ_i9WGfQ](url)

After trying out other combinations, I believe there is an issue with an istiofied deployment connecting to a headless service that is not wrapped with istio. I say this because I am able to connect to an non-istiofied deployment with a regular service. 

I've included the envoy config file from the pod. There aren't any errors, just my service hangs while waiting to connect to the other service and it restarts after a while. This does not happen if I deploy it without wrapping it with Istio.

https://gist.github.com/FuzzOli87/27519f99dbfeea8e6c327ec87a97143d

**Comment by rshriram** [comment]
Thanks!

Are you using --includeIPRanges by any chance while istiofying the NodeJS
pod?
The gist doesn't show the istiofied deployment. I don't see Envoy sidecar
in the spec.


@kyessenov @ayj the config looks about right. Configs are being generated
for Kafka services on 9091/9092 etc. Any thoughts?


-- 

~shriram

**Comment by FuzzOli87** [comment]
@rshriram I've updated the gist with the istiofied file generated by istioctl.

And no, I'm not using --includeIPRanges option when creating the istiofied deployment.

**Comment by hollinwilkins** [comment]
Allowing services within the mesh to reach services outside the mesh would be incredibly useful. It seems possible right now to do this with an egress, but that only supports HTTP and is a possible bottleneck. Some reasons that resolving this issue would be very important is as follows:

1. Using non-HTTP hosted solutions where we integrate by creating a service in Kubernetes that points to the DNS records of the hosted solution
2. Using Helm charts for services like RabbitMQ, CockroachDB, Postgres, MySQL, etc. These services are non-HTTP and created outside of the service mesh

From a user perspective, I wouldn't mind either:
a. Setting up some Envoy proxies to these services so that Istio can still track them and I can integrate them into the mesh this way
b. A direct passthrough to regular services without any proxying (probably desirable for performance and flexibility)

**Comment by rshriram** [comment]
Hi, we are looking into fixing this. The primary issue seems to be dealing with headless services. @vadimeisenbergibm is working on this.

**Comment by astanciu** [comment]
Any updates on this? Is still not possible to use Istio if using something like RabbitMQ?

**Comment by prune998** [comment]
I think it's fixed. Try it.

**Comment by ldemailly** [comment]
egress is still wip but closing this for now

**Comment by boeboe** [comment]
@hollinwilkins @FuzzOli87 

Probably a stupid question, but why don't your run those services within the mesh? This seems to have a lot of added benefits at first sight, no... (the most obvious one being authn/z)?

**Comment by sebastian-garofalo** [comment]
Any updates? Is it possible to configure an Egress with AMQP? I have been trying it but only get connections reset by peer with RabbitMQ reporting a bad_header error.

**Comment by ldemailly** [comment]
It should, can you file a new issue in istio/istio if it's not working for you with 0.8
